config/routes.rb
Rails.application.routes.draw do


  devise_for :users, path: '', :path_names => { sign_in: '/', sign_out: 'sign_out'}, :controllers => { :registrations => :registrations, :omniauth_callbacks => "omniauth_callbacks" }, skip: :registrations
    as :user do
      get "users/cancel", to: "registrations#cancel", as: :cancel_user_registration
      get "users/sign_up", to: "registrations#new", as: :new_user_registration
      get "/users/edit", to: "registrations#edit", as: :edit_user_registration
      post "/users", to: "registrations#create"
      delete "/users", to: "registrations#destroy"
      patch "/users", to: "registrations#update", as: :user_registration
      put "/users", to: "registrations#update"
    end


  root 'devise/sessions#new'

  resources :users do
    resources :appointments
  end

  get "/users", to: 'users#index'


  resources :rabbis

  mount ActionCable.server, at: '/cable'


end

app/models/rabbi.rb
class Rabbi < ApplicationRecord

  
  validates :first_name, :last_name, presence: true
  validates :first_name, uniqueness: {scope: :last_name}

  has_many :appointments, inverse_of: :rabbi, dependent: :destroy
  has_many :users, through: :appointments

  def future_appointments
    appointments.where("time_and_date > ?", Time.current)
  end

  def client_count
    users.distinct.count
  end

end

app/controllers/rabbis_controller.rb
class RabbisController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @rabbis = Rabbi.all
    @rabbi = Rabbi.new
  end

  def new
    @rabbi = Rabbi.new
  end

  def show
    @rabbi = Rabbi.find(params[:id])
    @upcoming_appoitments_count = @rabbi.future_appointments.count
    respond_to do |response|
      response.html {render :show}
      response.json {render json: @rabbi}
    end

  end

  def create
    @rabbi = Rabbi.new(rabbi_params)
    if @rabbi.save
      respond_to do |response|
        response.html {redirect_to rabbi_path(@rabbi)}
        response.json {render json: { rabbi: @rabbi, isAdmin: current_user.admin? }}
      end
    else
      respond_to do |response|
        response.html { render :new }
        response.json {render json: "invalid input"}
      end
    end
  end

  def edit
    @rabbi = Rabbi.find(params[:id])
  end

  def update
    @rabbi = Rabbi.find(params[:id])

    if @rabbi.update(rabbi_params)
      redirect_to rabbi_path(@rabbi), alert: "Sucssefully updated Rabbi profile."
    else
      render :edit
    end

  end


  def destroy

    @rabbi = Rabbi.find(params[:id])
    @rabbi.destroy!
    render json: {status: 201, rabbi_id: @rabbi.id}

    #redirect_to rabbis_path, alert: "Sucssefully delteted Rabbi."
  end

  private

  def rabbi_params
    params.require(:rabbi).permit(:first_name, :last_name, :dob, :branch_of_judaism, :charisma_level)
  end

end

app/helpers/rabbis_helper.rb
module RabbisHelper
end

app/views/rabbis/_form.html.erb
<% if @rabbi.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@rabbi.errors.count, "error") %> prohibited this appointment from being saved:</h2>

    <ul>
    <% @rabbi.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @rabbi, id: "new_rabbi" do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %><br><br>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %><br><br>

  <%= f.label :dob, "Date of Birth:" %>
  <%= f.date_field :dob %><br><br>

  <%= f.label :branch_of_judaism %>
  <%= f.text_field :branch_of_judaism %><br><br>

  <%= f.label :charisma_level %>
  <%= f.select(:charisma_level, options_for_select([['1',1], ['2',2], ['3',3], ['4',4], ['5',5]], f.object.charisma_level )) %><br><br>

  <%= f.submit data: { disable_with: false }  %>

<% end %>

app/views/rabbis/edit.html.erb
<h1>Edit Rabbi</h1>
<%= render 'form' %>

app/views/rabbis/index.html.erb
<div id='rabbi-index'>
  <h1>Find a Rabbi</h1>



  <ol>
    <% @rabbis.each do |rabbi| %>
      <div id class="rabbi">
        <p><li><%= link_to "Rabbi #{rabbi.first_name} #{rabbi.last_name}", rabbi_path(rabbi)%> Charisma Level: <%= rabbi.charisma_level%> <br> <%= button_tag "Delete", class: 'delete-rabbi', type: 'button', "data-rabbi-id": rabbi.id if current_user.admin?  %>
          </li></p>
        </div>
      <% end %>
    </ol>


  <h3>Missing your Rabbi??</h3>
  <h3>Add one here:</h3>

   <%= render 'form' %>
</div>

app/views/rabbis/new.html.erb
<h1>New Rabbi Form</h1>
<%= render 'form' %>

app/views/rabbis/show.html.erb
<div class="container">
<h1>Rabbi <%= @rabbi.last_name %>'s Profile</h1>

<p>Birthday: <%= @rabbi.dob.strftime("%A, %B %d, %Y") if @rabbi.dob %></p>

<p>Affiliated Branch of Judaisim: <%= @rabbi.branch_of_judaism %></p>

<p>Charisma Level: <%= @rabbi.charisma_level %></p>

<p>You have <%= pluralize(@upcoming_appoitments_count, "appointment")%> and <%= pluralize(@rabbi.client_count, "client")%>.  </p>

</p>

<%= button_tag "Message the Rabbi" %> 

<p><%= link_to "Edit Rabbi", edit_rabbi_path(@rabbi)%></p>

<%= link_to "Back", :back %>


</div>