config/routes.rb
Rails.application.routes.draw do


  devise_for :users, path: '', :path_names => { sign_in: '/', sign_out: 'sign_out'}, :controllers => { :registrations => :registrations, :omniauth_callbacks => "omniauth_callbacks" }, skip: :registrations
    as :user do
      get "users/cancel", to: "registrations#cancel", as: :cancel_user_registration
      get "users/sign_up", to: "registrations#new", as: :new_user_registration
      get "/users/edit", to: "registrations#edit", as: :edit_user_registration
      post "/users", to: "registrations#create"
      delete "/users", to: "registrations#destroy"
      patch "/users", to: "registrations#update", as: :user_registration
      put "/users", to: "registrations#update"
    end


  root 'devise/sessions#new'

  resources :users do
    resources :appointments
  end

  get "/users", to: 'users#index'


  resources :rabbis

  mount ActionCable.server, at: '/cable'


end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :rabbi
  belongs_to :service

  validates :time_and_date, :service_id, presence: true
  accepts_nested_attributes_for :rabbi

  validate :does_not_conflict_other_appointments, :during_regular_hours, :not_on_saturday




  scope :future_appointments, -> (user_id) {where("user_id = ? AND time_and_date > ?",user_id, Time.current )}



  def rabbi_attributes=(attributes)
    self.rabbi = Rabbi.find_or_create_by(attributes)
  end




  private


  def does_not_conflict_other_appointments
    errors.add(:time_and_date, "already taken by another appointment") if time_and_date &&  rabbi.appointments.where(time_and_date: (time_and_date - 15.minutes..time_and_date + 1.hours)).where.not(user_id: user_id).exists?
  end

  def during_regular_hours
    errors.add(:time_and_date, "Not between hours 8:30 AM - 6:30 PM") unless time_and_date && time_and_date.strftime("%H%M").to_i >= 830 && time_and_date.strftime("%H%M").to_i <= 1830
  end

  def not_on_saturday
    errors.add(:time_and_date, "can not be on saturday") if time_and_date && time_and_date.saturday?
  end





end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource :user
  load_and_authorize_resource :appointment, :through => :user

  before_action :set_user

  def index
    @appointments = Appointment.future_appointments(@user.id)
    respond_to do |response|
      response.html {render :index}
      response.json {render json: @appointments}
    end
  end

  def new
    @appointment = @user.appointments.build
    @rabbi = Rabbi.new
  end

  def create
    @appointment = @user.appointments.build(appointment_params)
    if @appointment.save
        redirect_to user_appointment_path(@user, @appointment)
    else
      render :new
    end

  end

  def show
    @appointment = @user.appointments.find(params[:id])
  end

  def edit
    @appointment = @user.appointments.find(params[:id])
  end

  def update
    @appointment = Appointment.find_by(id: params[:id])


    if @appointment.update(appointment_params)
      redirect_to user_appointment_path(@user, @appointment)
    else
      render "edit"
    end

  end

  def destroy
    @appointment = @user.appointments.find(params[:id])
    @appointment.destroy

    redirect_to user_appointments_path(@user)


  end


  private

  def appointment_params
    params.require(:appointment).permit(:rabbi_id, :service_id, :time_and_date, :time, :date, rabbi_attributes: [:first_name, :last_name])
  end


  def set_user
    @user = User.find_by(id: params[:user_id])
  end


end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<div name='form-wrapper' class="w-25 px-5 py-1  mx-auto bg-info rounded">

  <h3 class="text-center p-4 text-white "> <%= heading %> </h3>

  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h4>

      <ul>
      <% @appointment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



    <%= form_for [@user, @appointment] do |f| %>
      <%= f.fields_for :rabbi, @rabbi do |r| %>

          <div class="field form-group">
            <%= r.text_field :first_name, placeholder: "Rabbi's first name", class: 'form-control'  %>
          </div>
          <div class="field form-group">
            <%= r.text_field :last_name, placeholder: "Rabbi's last Name", class: 'form-control' %>
          </div>
        <% end %>

    <div class="field form-group">
      <%= f.collection_select(:service_id, Service.all ,:id, :name, {:prompt => 'Select a purpose'}, class: 'form-control-sm' ) %>
    </div>



    <div class="field form-group">
      <%= f.date_select :time_and_date, {prompt: true, start_year: Date.current.year, end_year: Date.current.year + 1, order: [:day, :month, :year]}, {class: 'form-control-sm'} %>
    </div>

    <div class="field form-group">
      <%= f.time_select :time_and_date, {ampm: true , ignore_date: true, minute_step: 15, prompt: true }, {class: 'form-control-sm'}%>
    </div>


    <div class="action form-group">
      <%=f.submit nil, class: 'btn btn-primary' %>
    </div>



  <%end %>
</div>

app/views/appointments/edit.html.erb
<%= render partial: "form", locals: {heading: "Edit Appointment" } %>

app/views/appointments/index.html.erb
<% if @appointments.blank? %>
<div class="w-50 bg-light m-auto p-3 rounded text-center">
  <p class="m-0">You don't have any upcoming appointments yet. <strong><%= link_to "Make an appointment", new_user_appointment_path(@user)%></strong> with your rabbi now!</p>
</div>

  <% else %>
  <h2 class="display-4 w-50 m-auto text-center"><%=@user.name%>'s Future Appointments</h2>
    <% @appointments.each do |appointment| %>
    <div class="appointment mx-auto my-3 w-50 bg-light p-3 rounded">


      <p>Date: <%=appointment.time_and_date.strftime("%A, %B %d, %Y")%></p>
      <p>Time: <%=appointment.time_and_date.strftime("%I:%M %p")%></p>
      <p>Service: <%=appointment.service.name%></p>
      <%= link_to "View Summary", user_appointment_path(appointment.user, appointment), class: 'btn btn-success'%>
    </div>
    <% end %>
  <% end %>

app/views/appointments/new.html.erb
  <%= render partial: 'form', locals: {heading: "Schedule Appointment"} %>

app/views/appointments/show.html.erb
<div class="w-50 p-4 m-auto bg-light rounded">
  <h2>Appointment Summary</h2>
  <p>Rabbi: <%= link_to "#{@appointment.rabbi.first_name} #{@appointment.rabbi.last_name}", rabbi_path(@appointment.rabbi) %></p>
  <p>Time: <%= @appointment.time_and_date.strftime("%I:%M %p") %></p>
  <p>Date: <%= @appointment.time_and_date.strftime("%A, %B %d, %Y") %></p>
  <p>Reason: <%= @appointment.service.name %></p>
  <p>For: <%= @user.name %></p>


  <%= button_to "Cancel Appointment" , {action: "destroy"}, method: :delete, class: "btn btn-danger ", form_class: "d-inline pr-1"   %>
  <%= button_to "Edit Appointment" ,edit_user_appointment_path(@appointment.user, @appointment), method: :get, class: "btn btn-success", form_class: "d-inline pl-1"   %>

</div>