config/routes.rb
Rails.application.routes.draw do


  devise_for :users, path: '', :path_names => { sign_in: '/', sign_out: 'sign_out'}, :controllers => { :registrations => :registrations, :omniauth_callbacks => "omniauth_callbacks" }, skip: :registrations
    as :user do
      get "users/cancel", to: "registrations#cancel", as: :cancel_user_registration
      get "users/sign_up", to: "registrations#new", as: :new_user_registration
      get "/users/edit", to: "registrations#edit", as: :edit_user_registration
      post "/users", to: "registrations#create"
      delete "/users", to: "registrations#destroy"
      patch "/users", to: "registrations#update", as: :user_registration
      put "/users", to: "registrations#update"
    end


  root 'devise/sessions#new'

  resources :users do
    resources :appointments
  end

  get "/users", to: 'users#index'


  resources :rabbis

  mount ActionCable.server, at: '/cable'


end

app/views/layouts/_nav_bar.html.erb
<% if user_signed_in? %>
    <nav class="navbar  navbar-expand-lg navbar-light bg-light" >
      <%= link_to "Rabbi Appointment Tracker", user_path(current_user), class: "navbar-brand" %>
      <div class="collapse navbar-collapse" >
        <ul class="navbar-nav mr-auto" >
          <li class="nav-item " >
            <%= link_to "Upcoming Appointments", user_appointments_path(current_user), class: 'nav-link'  %>
          </li>
          <li class="nav-item" >
            <%= link_to "Make an Appointment", new_user_appointment_path(current_user), class: 'nav-link' %>
          </li>

          <li class="nav-item" >
            <%= link_to "Your Profile", user_path(current_user), class: 'nav-link' %>
          </li>

          <li class="nav-item" >
            <%= link_to "Find a Rabbi", rabbis_path, class: 'nav-link' %>
          </li>

          <li class="nav-item" >
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'nav-link' %>

          </li>
        </ul>
      </div>
    </nav>
<% else %>
<nav class="navbar navbar-expand-lg  navbar-light bg-light">
  <a class="navbar-brand">Rabbi Appointment Tracker</a>
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign In", new_user_session_path, class: 'nav-link' %>
      </li>
    </ul>

  </div>
</nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rabbi Appointment Tracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= yield :cable %>


  </head>

  <body>
    <%= render 'layouts/nav_bar' %>
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>